name:                yesod-hash-static
version:             0.1.0.0
github:              "githubuser/yesod-hash-static"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/yesod-hash-static#readme>

dependencies:
- base >= 4.7 && < 5
- yesod-static
- async
- attoparsec            >= 0.10
- base64-bytestring     >= 0.1.0.1
- blaze-builder         >= 0.3
- bytestring            >= 0.9.1.4
- conduit               >= 1.3
- containers            >= 0.2
- cryptonite            >= 0.11
- cryptonite-conduit    >= 0.1
- css-text              >= 0.1.2
- data-default
- directory             >= 1.0
- file-embed            >= 0.0.4.1  && < 0.5
- filepath              >= 1.3
- hashable              >= 1.1
- hjsmin
- http-types            >= 0.7
- memory
- mime-types            >= 0.1
- process
- template-haskell
- text                  >= 0.9
- transformers          >= 0.2.2
- unix-compat           >= 0.2
- unordered-containers  >= 0.2
- wai                   >= 1.3
- wai-app-static        >= 3.1
- yesod-core            >= 1.6      && < 1.7

library:
  source-dirs: src
  ghc-options: -Wall

